name: Deploy code

# When to run

on:
  push:
    branches:
      - main

# What to do

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy code
        run: npm run deploy
